# 开发环境配置文件
logging:
  config: classpath:logback/logback-dev.xml

server:
  port: 8081     # Springboot占用端口
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver     # 数据库驱动
      url: jdbc:mysql://rm-wz9z9aapfh7hud44kho.mysql.rds.aliyuncs.com:3306/dami-dev?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false     # 数据库链接
      username: dami_dev     # 数据库账号
      password: cbRNueDlFeDOacOo     # 数据库密码
  devtools:
    restart:
      enabled: true     # 开启热更新